### ISSUE TITLE
Question:  Is Packer now going to be supported as a tool on the deployment nodes

### ISSUE THREAD

**Issue by Marcus-James-Adams** [OctopusDeploy/Octopus.Dependencies.Packer#2]
Is Packer now going to be supported as a tool on the deployment nodes?

If so I'm happy to give a got at writing the community templates to take advantage of it.

**Comment by mcasperson** [comment]
Hi @Marcus-James-Adams, unfortunately we don't have plans to add support for packer as a first class step at this time. The additional package references documented at https://octopus.com/blog/script-step-packages is the preferred approach for including tooling like Packer now.
